### ISSUE TITLE
How to train on rgbd dataset?

### ISSUE THREAD

**Issue by JimXu1989** [bowu1004/instance_segmentation_RealSense#1]
Hello,
Thank you for sharing the great work with us,
I want to know how to train on my own dataset? And could the D channel in float format?

Thanks a lot !!

**Comment by bowu1004** [comment]
Hey, I hope you found this useful to train your own data. I used to refer to 1. https://www.dlology.com/blog/how-to-create-custom-coco-data-set-for-instance-segmentation/ and 2. https://www.dlology.com/blog/how-to-train-detectron2-with-custom-coco-datasets/. Please let me know if that helps. Regarding the D channel, yes, it can be float format. You can convert it to float if you get something like Int8 or Int16.
