### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by akshayacharya97** [bowu1004/instance_segmentation_RealSense#2]
When I run the main.py file, it runs fine when there are no objects detected, how ever, the moment an object is detected, it crashes and the gives the following output
```
Traceback (most recent call last):
  File "main_detectron2_simple_mac.py", line 542, in <module>
    tracked_objects = mot_tracker.update(boxes_list)
  File "/home/akshay/detectron2/sort.py", line 249, in update
    matched, unmatched_dets, unmatched_trks = associate_detections_to_trackers(dets,trks)
  File "/home/akshay/detectron2/sort.py", line 190, in associate_detections_to_trackers
    if(d not in matched_indices[:,0]):
TypeError: tuple indices must be integers or slices, not tuple
```
Why is it not continuing after object is detected

**Comment by bowu1004** [comment]
It seems to be me as a format problem. You may check the format and type in step-by-step debug mode. Hope this webpage from stackoverflow, https://stackoverflow.com/questions/39839034/python-tuple-indices-must-be-integers-not-tuple, also helps.
