### ISSUE TITLE
No module named 'detectron2.engine'

### ISSUE THREAD

**Issue by bn2022** [bowu1004/instance_segmentation_RealSense#4]
Hi 
I am receiving this error while running  main_detectron2_simple_win10.py :

No module named 'detectron2.engine'

how can I solve it?

**Comment by bowu1004** [comment]
The error says that you haven't installed Detectron2. Please refer to the subsection of "Build Detectron2" at the README.md file. If it still reports errors, please refer to the official website of Dectectron2 at https://github.com/facebookresearch/detectron2 for installation instructions.
